### ISSUE TITLE
Dockerfile  user non root

### ISSUE THREAD

**Issue by Rehzende** [IsraelHikingMap/graphhopper-docker-image-push#1]
Is it possible to run the container with another user other than root?

**Comment by HarelM** [comment]
The code here is open, you can do what docker offers by changing the code here.
Not sure I understand the question...

**Comment by zstadler** [comment]
You may use the `--user` flag, as described in https://docs.docker.com/engine/reference/run/#user

**Comment by Rehzende** [comment]
I understand, but can I use a non-root user to run the application?

**Comment by HarelM** [comment]
Try and let us know... We haven't tested it.

**Comment by Rehzende** [comment]
right!
I did the test adding the parameters below and it worked. Thank you all.
```
RUN addgroup   --system --gid 1001 graphhopper && \
    adduser  --system --uid  1001   --group graphhopper && \
    chown -R graphhopper:graphhopper /graphhopper 
USER graphhopper
```
