### ISSUE TITLE
Image not published?

### ISSUE THREAD

**Issue by rkube-rvk** [IsraelHikingMap/graphhopper-docker-image-push#17]
Still not sure, but...
I think the image build by the 'github action' is not getting uploaded to dockerhub because the upstream graphhopper version did not changed yet.

**Comment by HarelM** [comment]
The image was not pushed due to missing support for chmod apparently... :-(

**Comment by HarelM** [comment]
I'm not sure this is the right solution. I also don't remember that this was needed in the past.
I'll remove the chmod and see what happens tomorrow...

**Comment by HarelM** [comment]
Still not fixed, the image fails to find the jar file. I was sure I solved it already... Weird...
I'll take care of this tonight.

**Comment by HarelM** [comment]
I think the latest image is now fine.
For example:
```
docker run -p 8989:8989 israelhikingmap/graphhopper:latest --url https://download.geofabrik.de/europe/andorra-latest.osm.pbf --host 0.0.0.0
```
and in order to create a routing cache folder one can run the following command (needs a `-v` parameter probably)
```
docker run -p 8989:8989 israelhikingmap/graphhopper:latest --url https://download.geofabrik.de/europe/andorra-latest.osm.pbf --host 0.0.0.0 --import
```

**Comment by HarelM** [comment]
If this is still not working please let me know and I'll reopen this issue.
