### ISSUE TITLE
example under Linux

### ISSUE THREAD

**Issue by karussell** [IsraelHikingMap/graphhopper-docker-image-push#18]
With the current example command:

```
sudo docker run --entrypoint /bin/bash israelhikingmap/graphhopper -c "wget https://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf -O /data/berlin.osm.pbf && java -Ddw.graphhopper.datareader.file=/data/berlin.osm.pbf -Ddw.graphhopper.graph.location=berlin-gh -jar *.jar server config-example.yml" 
```

I was able to start the import process and the server, but I wasn't able to access the service at https://localhost:8989/

I tried it via the `--host 0.0.0.0` parameter or the port mapping `-p 8989:8989` but without success. The only thing that worked was using the host network (`--net="host"`). (Maybe I should bind the GraphHopper service in the container to 0.0.0.0 via changing the config-example.yml, not sure.)

Also when I stop the service and restart it with the same command then it does the entire import again. I can avoid this via mounting a volume and downloading the pbf outside of the container like this:

```
wget https://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf -O berlin.osm.pbf
docker run -v $(pwd)/:/data/ --entrypoint /bin/sh israelhikingmap/graphhopper -c "java -Ddw.graphhopper.datareader.file=/data/berlin.osm.pbf -Ddw.graphhopper.graph.location=/data/berlin-gh -jar *.jar server config-example.yml"
```

**Comment by HarelM** [comment]
You need to both bind graphhopper to 0.0.0.0 and expose 8989 of the container.
You'll need a volume for persistence in order to avoid the import again, this is how docker works.
I don't see an issue here though...?

**Comment by karussell** [comment]
Sorry, I have too few docker experience. The last command in the readme (that swaps the entrypoint) was confusing for me as it does not work (under Linux) even if you map the ports via `-p 8989:8989`. I would have expected an example that works under linux similar to how you can [start it natively](https://github.com/graphhopper/graphhopper#installation).

And I think the following command is one that I would have expected:

```
sudo docker run -v $(pwd)/:/data/ -p 8989:8989 israelhikingmap/graphhopper -i /data/berlin.pbf -o /data/berlin-gh -c /data/config-example.yml
```

Obviously this requires you to download the pbf and the config-example.yml beforehand but it does not do the import twice.
