### ISSUE TITLE
Out of memoy exception coming

### ISSUE THREAD

**Issue by umar18** [IsraelHikingMap/graphhopper-docker-image-push#21]
I am trying with US map to deploy docker but it is giving me following error:

![Untitled](https://user-images.githubusercontent.com/3582080/178939041-8d37f934-ae67-4652-8e55-e83ae58812a7.jpg)

Is it due to the memory ? I have 40GB of RAM installed.

**Comment by HarelM** [comment]
There are two aspects here - 1 how much memory you defined to docker.
2 how much memory was allocated to the JVM.
In any case, this is configurable for both and need to be increased I guess.

**Comment by umar18** [comment]
I think by default if memory limitation is not defined then all available memory is available to docker. or is not ?

**Comment by umar18** [comment]
Thanks. Actually i am a newbie to docker and all this stuff, can you please tell me how to set env variables ?

**Comment by HarelM** [comment]
Dude... google... come on... :-)

**Comment by umar18** [comment]
Thanks for your help, it worked.
