### ISSUE TITLE
How to use built in profiles

### ISSUE THREAD

**Issue by umar18** [IsraelHikingMap/graphhopper-docker-image-push#22]
I have successfully deployed docker container on my Linux machine with default “car” profile. In the documentation: https://docs.graphhopper.com/#section/Map-Data-and-Routing-Profiles/OpenStreetMap, i can see multiple built in profile. Can i integrate multiple profiles ? How can i do that in docker run command ? I can see profile option with coma separated profiles but its not working. Here is the command:

docker run -p 8989:8989 israelhikingmap/graphhopper --url https://download.geofabrik.de/europe/andorra-latest.osm.pbf --host 0.0.0.0 -p|--profiles car,bike

**Comment by HarelM** [comment]
Can you share the container logs - it should log which profiles it is about to build according to the given configuration.

**Comment by umar18** [comment]
It is behaving oddly 

![image](https://user-images.githubusercontent.com/3582080/179529205-c9736260-98e2-49f2-9710-be777073dcc7.png)

**Comment by HarelM** [comment]
This is not the logs I was expecting to see. What are the logs you are getting when simply running the container (not in a detached mode)?

**Comment by umar18** [comment]
Oh, you mean this one

![image](https://user-images.githubusercontent.com/3582080/179543531-d31122ab-59fe-439d-b84f-8dda92cb4649.png)

**Comment by HarelM** [comment]
Nope... The graphipper container run log

**Comment by HarelM** [comment]
No response... Closing...
