### ISSUE TITLE
ARM64 images

### ISSUE THREAD

**Issue by jtbaker** [IsraelHikingMap/graphhopper-docker-image-push#26]
Hi, thanks for your work on this! Would you be open to modifying the Actions pipeline to push arm64 versions of this image to the registry as well?

**Comment by HarelM** [comment]
Sure, feel free to open a PR.

**Comment by HarelM** [comment]
@jtbaker my old mac dies and I bought a new one with M2, seems like the graphhopper image isn't able to finish importing.
How did you solve the problem? Did you do anything special besides upgrading Docker desktop for mac?

**Comment by HarelM** [comment]
Seems like a restart solved this.
Can I close this issue? I don't see a good need at this point to complicate things if apple and docker solved this by their own...

**Comment by HarelM** [comment]
Basically this tutorial:
https://collabnix.com/warning-the-requested-images-platform-linux-amd64-does-not-match-the-detected-host-platform-linux-arm64-v8/
<img width="927" alt="image" src="https://user-images.githubusercontent.com/3269297/230912075-9f2f7e5d-9d49-4640-87ad-467a7bb07790.png">

**Comment by HarelM** [comment]
Closing, if anyone is interested, feel free to open a PR.
