### ISSUE TITLE
can't build, missing files to build?

### ISSUE THREAD

**Issue by albjeremias** [IsraelHikingMap/graphhopper-docker-image-push#28]
on the Dockerfile line 17... its copying some files from somewhere.. how do I get this files? 

````
$ docker build -t graphhopper .
Sending build context to Docker daemon  102.4kB
Step 1/15 : FROM maven:3.6.3-jdk-8 as build
 ---> d1b3f61d61f2
Step 2/15 : WORKDIR /graphhopper
 ---> Using cache
 ---> bcbf97944ea4
Step 3/15 : COPY graphhopper .
COPY failed: file not found in build context or excluded by .dockerignore: stat graphhopper: file does not exist
````

https://github.com/IsraelHikingMap/graphhopper-docker-image-push/blob/main/Dockerfile#L17

**Comment by HarelM** [comment]
You should use build.sh - it clones and builds graphhopper from their repo.
Also note that this repo builds graphhopper on a daily basis and pushes that to dockerhub, so I'm not sure why would you want to build it locally...

**Comment by albjeremias** [comment]
ok, can u point me to the dockerhub image? or documentation on how-to set this up. i can't find it anywhere.. i've been hopping from repo to repo.. i just need 

localhost:8989/ 

The idea is:

I'm developing this open source tool:
https://github.com/helpbuttons/helpbuttons

the idea is that when setting up the webapp, on the configuration page, there would be a multiple choice so maps would download, and be ready to use on the server. 

in resume:
How do I run this using docker-compose? I don't understand.

**Comment by albjeremias** [comment]
So I added this image to my docker-compose.yml

https://github.com/helpbuttons/helpbuttons/blob/graphhopper/docker-compose.yml#L33

Try to run it using:
docker-compose graphhopper

got this error:
````
$ docker-compose up bb
WARNING: Found orphan containers (helpbuttonsorg_graphhopper_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Creating helpbuttonsorg_bb_1 ... error

ERROR: for helpbuttonsorg_bb_1  Cannot start service bb: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: exec: "./graphhopper.sh": permission denied: unknown

ERROR: for bb  Cannot start service bb: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: exec: "./graphhopper.sh": permission denied: unknown
ERROR: Encountered errors while bringing up the project.
```

**Comment by HarelM** [comment]
Did you try out what the readme in this repo explains? Did it not work?
This is my dicker compose:
https://github.com/IsraelHikingMap/Site/blob/b5cabb95246d0327f3399ba8fd698b98d51ebb78/docker-compose.yml#L26
And here's is the script to creat a routing graph that needs to run before the first up command:
https://github.com/IsraelHikingMap/Site/blob/b5cabb95246d0327f3399ba8fd698b98d51ebb78/gh-update.ps1

**Comment by albjeremias** [comment]
cool. i will try it. anyway i recommend to add this line in your Dockerfile:

`RUN chmod +x ./graphhopper.sh`

you probably always deploy from the same machine, try to run all the deploy from a blank machine, you will bump into this problem ;)

**Comment by albjeremias** [comment]
I setup the docker-compose entrypoint like this:

   entrypoint: bash -c "chmod +x ./graphhopper.sh && ./graphhopper.sh --host 0.0.0.0 -i ignore.pbf -o /data/default-gh/ -c /data/gh-config.yml"
   
   and it works.. also made a PR ;)
