### ISSUE TITLE
Consolidate build scripts

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/graphhopper-docker-image-push#32]
- Modify `build-and-publish.sh` to use `build.sh`. 
- Modify `build.sh` to accept an optional `--publish` flag to further simplify its use by `build-and-publish.sh`.

To be implemented after #27 is resolved

**Comment by HarelM** [comment]
PR #27 was closed. Feel free to refactor the scripts. :-)

**Comment by HarelM** [comment]
This was addressed as far as I can tell.
