### ISSUE TITLE
Profiles don't seem to work

### ISSUE THREAD

**Issue by vasily-polonsky** [IsraelHikingMap/graphhopper-docker-image-push#34]
Hi there,

I try to run on the docker image, it runs fine. The problem is that only the car profile is available. The command I use is as follows
`docker run -p 8989:8989 israelhikingmap/graphhopper --url https://download.geofabrik.de/europe/andorra-latest.osm.pbf --host 0.0.0.0 --profiles car,bike,foot`

In UI I see only car option, when I send the request I get this response. 

`curl --location --request POST 'http://localhost:8989/route?key=' \
--header 'Content-Type: application/json' \
--data-raw '{
   "points": [
    [
     37.629913, 55.751231
    ],
    [
      37.63914,55.742873
    ]
  ],
  "profile": "foot",
  "elevation": true,
  "debug": false,
  "instructions": true,
  "locale": "de_DE",
  "optimize": "false",
  "points_encoded": true,
  "snap_preventions": [
    "ferry"
  ],
  "details": [
    "road_class",
    "road_environment",
    "max_speed",
    "average_speed"
  ],
  "alternative_route.max_paths": 3,
  "algorithm": "alternative_route"
}'`

Tried with another card, same result, can you give advice or is it a mistake?

**Comment by HarelM** [comment]
Yea, profile flag broke in the last version, we should remove it from the script I guess.
You need to create a gh config yaml file and mount it into the container to properly define the profiles you would like.

**Comment by montarion** [comment]
just checking if I'm doing something wrong, is this still broken?

i'm doing a GET /profiles and the server returns 404

**Comment by HarelM** [comment]
Sending a request to graphhopper and getting back 404 is not related to the code in this repo that just wraps the java cli with docker and adds some basic script for ease of use to run the CLI.

**Comment by montarion** [comment]
> Sending a request to graphhopper and getting back 404 is not related to the code in this repo that just wraps the java cli with docker and adds some basic script for ease of use to run the CLI.

Got it, thanks!
