### ISSUE TITLE
graphhopper Error pull access denied for graphhop... 

### ISSUE THREAD

**Issue by gbrigens** [IsraelHikingMap/graphhopper-docker-image-push#36]
I am running the project after cloning, unfortunately I am experiencing this error "Error response from daemon: pull access denied for graphhopper/graphhopper, repository does not exist or may require 'docker login': denied: requested access to the resource is denied". After several failures I had to go to the docker hub and did not find this image specified as shown: "image: graphhopper/graphhopper:1.0". Is there an image you would recommend to fix this problem? thanks

![Screenshot 2024-04-17 at 14 40 13](https://github.com/IsraelHikingMap/graphhopper-docker-image-push/assets/4210156/185f380d-f271-49a1-9c83-ebba3da3388c)
![Screenshot 2024-04-17 at 14 40 49](https://github.com/IsraelHikingMap/graphhopper-docker-image-push/assets/4210156/2d479d6f-905b-412a-adb2-1e9217d10a9d)

**Comment by HarelM** [comment]
graphhopper doesn't publish an official image.
The image name is israelhikingmap/graphhopper
This is the image that is specified in the readme too.
https://hub.docker.com/r/israelhikingmap/graphhopper/tags
Also version 1.0 is super old and I don't think we created an image back then.
