### ISSUE TITLE
java.lang.IllegalArgumentException: Encoded values missing: road_access

### ISSUE THREAD

**Issue by g2giovanni** [IsraelHikingMap/graphhopper-docker-image-push#37]
Executing the Docker command outlined in the readme I get the following error:

`java.lang.IllegalArgumentException: Encoded values missing: road_access`

Any suggestion to solve the problem?

**Comment by HarelM** [comment]
You probably need a different config.yml file...

**Comment by HarelM** [comment]
Although we are using the exmaple config from the graphhopper repo, so I'm not sure what might go wrong.
Can you share the full command you ran?

**Comment by g2giovanni** [comment]
I used the commands in the readme without modification:

`docker run -p 8989:8989 israelhikingmap/graphhopper --url https://download.geofabrik.de/europe/andorra-latest.osm.pbf --host 0.0.0.0`

**Comment by HarelM** [comment]
You might want to use a specific version as this will run with latest master branch code, which might not be fully stable.
Did you try using an "official release"?

**Comment by HarelM** [comment]
The following seems to be working as expected:
`docker run -p 8989:8989 israelhikingmap/graphhopper:10.0 --url https://download.geofabrik.de/europe/andorra-latest.osm.pbf --host 0.0.0.0`
Note the 10.0 added to the docker image tag to take the latest official release.

**Comment by HarelM** [comment]
No response, closing, free free to comment and I'll be happy to reopen.
