### ISSUE TITLE
Multi Platform Build

### ISSUE THREAD

**Issue by jtbaker** [IsraelHikingMap/graphhopper-docker-image-push#40]
Continued discussion from https://github.com/IsraelHikingMap/graphhopper-docker-image-push/pull/38

@HarelM I got a successful build on my fork by keeping the changes from #38 and adding the `-DskipTests` flag to the `mvn clean install` command in the Dockerfile.

Do you think it is necessary to run the full test suite on each build? In their [quick start](https://github.com/graphhopper/graphhopper/blob/master/docs/core/quickstart-from-source.md) graphhopper seems to recommend providing that arg. I'm guessing that actually running the app to run the E2E tests is a much heavier workload that compiling it, especially on Github's limited free infrastructure.

Diff (I needed to pull the changes into my own `main` branch for GH to recognize the actions, and it wouldn't allow me to run the existing action, so I made a copy):
https://github.com/IsraelHikingMap/graphhopper-docker-image-push/compare/main...jtbaker:graphhopper-docker-image-push:main

https://github.com/jtbaker/graphhopper-docker-image-push/actions

If you think it is sufficient to not run the full test suite, we should be able to merge #41 as is.

**Comment by HarelM** [comment]
The reason I wanted to run the tests is to make sure the sticker image is valid before publishing it. I'm guessing the CI can do a sanity check of the image before pushing, maybe...?
I don't have strong feeling anyway...

**Comment by jtbaker** [comment]
Ah yeah. I don't think that running the tests through a vitualization engine will work on the GH CI options. I looked into having a separate action for the arm64 build that uses a native arm64 runner, but seems like Github only offers them those for enterprise accounts at the moment. Can just leave this PR/issue up until you decide what's best for the project.

**Comment by HarelM** [comment]
@jtbaker can you check if this works as expected?

**Comment by jtbaker** [comment]
@HarelM the ARM64 image is published on dockerhub now. I'm not in a position where I can test it right now, but you should be able to use it by providing the `--platform linux/arm64` argument to the docker `pull`/`run` commands.

![image](https://github.com/user-attachments/assets/a68b1dfc-fcbb-48ce-9e14-acb58239678c)

**Comment by jtbaker** [comment]
@HarelM I pulled down the latest image today on arm64 and everything went smoothly, just FYI. Also, I noticed the main graphhopper repo had [a bugfix release 10.2](https://github.com/graphhopper/graphhopper/releases/tag/10.2) a few months ago, but there doesn't seem to be an image build for it on the hub.docker.com registry this project pushes to. I guess those tagged pushes (other than `latest`) are manual and not triggered by CI? I couldn't find anything in the actions about pushing the tagged releases.

**Comment by HarelM** [comment]
@jtbaker this repo builds both the latest and the tagged versions, it checks as part of the CI if there was a version bump. 
Having said that, there might be a bug there.
Can you open a separate issue regarding the missing version?

**Comment by jtbaker** [comment]
> [@jtbaker](https://github.com/jtbaker) this repo builds both the latest and the tagged versions, it checks as part of the CI if there was a version bump. Having said that, there might be a bug there. Can you open a separate issue regarding the missing version?

Identified the issue and #44 opened to resolve.
